version "3.8"

services:
  nginx:
    build: ./requiriments/nginx
    container_name: nginx
    restart: always
    networks:
      - inception

  wordpress:
    build: ./requiriments/wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - ${HOST_DATA_PATH}/mariadb:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge
